[tool.ruff]
fix = true
select = [
    "E",
    "W",
    "F",
    "I",
    "C90",
    "N",
]
ignore = []
line-length = 120
exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "build",
    "dist",
    "*.egg-info",
]
