# Generated by Django 5.2.1 on 2025-05-29 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="URL прокси-сервера (e.g., http://user:pass@host:port)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время истечения срока действия прокси (опционально)",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent", models.TextField(help_text="Строка User-Agent", unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=200,
                        help_text="Статус использования прокси и User-agent",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                    ),
                ),
                (
                    "proxy",
                    models.ForeignKey(
                        help_text="Прокси-сервер, используемый для запросов",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="api.proxy",
                    ),
                ),
                (
                    "user_agent",
                    models.ForeignKey(
                        help_text="User-Agent, используемый для запросов",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="api.useragent",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_agent", "proxy")},
            },
        ),
    ]
