# Generated by Django 5.2.1 on 2025-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_proxy_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxy",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="URL прокси-сервера (e.g., http://user:pass@host:port)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
