# Generated by Django 5.2.1 on 2025-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_proxy_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxy",
            name="url_hash",
            field=models.CharField(
                default=1,
                editable=False,
                help_text="SHA-256 хеш URL для уникальности",
                max_length=64,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
