# Generated by Django 5.2.1 on 2025-05-30 11:47

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_proxy_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxy",
            name="url",
            field=api.fields.EncryptedCharField(
                blank=True,
                help_text="URL прокси-сервера (e.g., http://user:pass@host:port)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
